version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      -MONGO_INITDB_ROOT_USERNAME: root
      -MONGO_INITOB_ROOT_PASSWORD: root
      -MONGO_INITOB_DATABASE: product-service
    volumes:
      - C:/vol/mongo:/data/db
