version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: order_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - C:/vol/order_mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d/:rw