version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_inventory
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - C:/vol/mysql_inventory:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d/:rw